ARMOR_DATA = {
    "200": "Kamura Legacy Leggings",
    "001": "Leather Trousers X",
    "014": "Chainmail Pants X",
    "002": "Hunter's Greaves X",
    "044": "Dober Greaves X",
    "004": "Alloy Greaves X",
    "031": "Ingot Greaves X",
    "043": "Damascus Greaves",
    "238": "Melahoa Roots X",
    "239": "Makluva Pants X",
    "026": "Death Stench Heel X",
    "240": "Mosgharl Roots X",
    "241": "Rhopessa Crura X",
    "242": "Vaik Greaves X",
    "243": "Grand Chaos Plate",
    "244": "Edel Roots X",
    "245": "Spio Crura X",
    "246": "Medium's Hakama (Light)",
    "259": "Utsushi True Greaves (H)",
    "248": "S. Studded Sandals X",
    "249": "Jelly Boots X",
    "202": "Bishaten Greaves S",
    "203": "Aknosom Greaves S",
    "204": "Tetranadon Greaves S",
    "205": "Somnacanth Greaves S",
    "206": "Rakna Greaves",
    "207": "Goss Harag Greaves S",
    "208": "Almudron Greaves S",
    "209": "Ibushi's Foot",
    "210": "Narwa's Foot",
    "211": "Izuchi Greaves S",
    "047": "Kushala Crus",
    "212": "Mizuha Gaiters",
    "046": "Kaiser Greaves",
    "213": "Gargwa Mask X",
    "214": "Slagtoth Cloak X",
    "215": "Rhenoplos Greaves X",
    "216": "Jaggi Shinguards X",
    "217": "Bnahabra Boots X",
    "218": "Bullfango Mask X",
    "219": "Remobra Feet X",
    "220": "Droth Greaves X",
    "221": "Uroktor Coil X",
    "222": "Wroggi Greaves X",
    "223": "Baggi Greaves X",
    "224": "Arzuros Greaves X",
    "226": "Volvidon Greaves X",
    "227": "Ludroth Greaves S",
    "012": "Barroth Greaves S",
    "229": "Khezu Greaves S",
    "080": "Nargacuga Greaves S",
    "079": "Barioth Greaves S",
    "021": "Rathian Greaves S",
    "033": "Rathalos Greaves S",
    "083": "Tigrex Greaves S",
    "034": "Diablos Greaves S",
    "233": "Basarios Greaves S",
    "234": "Zinogre Greaves S",
    "235": "Golden Hakama",
    "237": "Valstrax Greaves",
    "009": "Kulu-Ya-Ku Greaves S",
    "010": "Pukei Greaves S",
    "011": "Jyuratodus Greaves",
    "013": "Kadachi Greaves S",
    "020": "Anjanath Greaves S",
    "042": "Bazelgeuse Greaves",
    "252": "Chrome Metal Boots X",
    "054": "Skull Visage X",
    "061": "Flame Seal",
    "255": "Black Leather Legs",
    "062": "Shadow Shades",
    "257": "Jaggi Mask X",
    "060": "Cunning Specs",
    "037": "Feather of Mastery",
    "201": "Sinister Greaves S",
    "225": "Lagombi Greaves X",
    "003": "Bone Greaves X",
    "228": "Mizutsune Greaves S",
    "036": "Brigade Boots X",
    "272": "Kamurai Leggings",
    "250": "Sinister Seal Greaves",
    "263": "Wyverian Earrings",
    "264": "Fox Mask",
    "262": "Theater Wig",
    "266": "Swallow Boots",
    "261": "Felyne Ears",
    "260": "Canyne Tail",
    "254": "Rider Greaves",
    "265": "Floral Zori",
    "276": "Akuma's Legs",
    "251": "Arthur's Greaves",
    "279": "Guild Cross Boots",
    "268": "Bombadgy Mask",
    "277": "Diver's Boots",
    "282": "Gorgeous Earrings",
    "283": "Spiribird Earrings",
    "284": "Woofpurr Earrings",
    "267": "Bunny Dango Earrings",
    "281": "Kunai Earrings",
    "289": "Orion Boots",
    "269": "Reverent Wrap",
    "285": "Bow Necklace",
    "286": "Leather Choker",
    "288": "Benevolent Bandage",
    "287": "Frilled Choker",
    "278": "Origin Greaves",
    "270": "Felyne Stealth Hood",
    "290": "Gala Suit Slacks",
    "291": "Blossom Boots",
    "280": "Black Belt Greaves",
    "271": "Kamura Cloak Braces",
    "292": "Sonic Shoes",
    "293": "Azure Age Geta",
    "433": "Black Belt Greaves S",
    "360": "Hornetaur Greaves",
    "359": "Vespoid Greaves",
    "358": "Velociprey Greaves",
    "310": "Izuchi Greaves X",
    "328": "Kulu-Ya-Ku Greaves X",
    "302": "Aknosom Greaves X",
    "315": "Ludroth Greaves X",
    "316": "Barroth Greaves X",
    "337": "Hermitaur Greaves",
    "303": "Tetranadon Greaves x",
    "385": "Five Element Legwear",
    "372": "Squire's Greaves",
    "388": "Yukumo Sky Hakama",
    "389": "Cohoot Mask",
    "317": "Khezu Greaves X",
    "301": "Bishaten Greaves X",
    "347": "Orangaten Greaves",
    "329": "Pukei Greaves X",
    "330": "Jyuratodus Greaves X",
    "324": "Basarios Greaves X",
    "304": "Somnacanth Greaves X",
    "348": "Auroracanth Greaves",
    "320": "Rathian Greaves X",
    "331": "Kadachi Greaves X",
    "332": "Anjanath Greaves X",
    "373": "Artillery Corps Greaves",
    "376": "Scholar's Socks",
    "386": "Guardian Boots",
    "390": "Monksnail Hat",
    "319": "Barioth Greaves X",
    "300": "Sinister Demon Greaves",
    "318": "Nargacuga Greaves X",
    "306": "Goss Harag Greaves X",
    "354": "Golm Greaves",
    "338": "Ceanataur Greaves",
    "307": "Almudron Greaves X",
    "350": "Magmadron Greaves",
    "305": "Rakna Greaves X",
    "349": "Pyre-Kadaki Greaves",
    "334": "Mizutsune Greaves X",
    "321": "Rathalos Greaves X",
    "325": "Zinogre Greaves X",
    "322": "Tigrex Greaves X",
    "323": "Diablos Greaves X",
    "341": "Gore Greaves",
    "343": "Regios Greaves",
    "344": "Astalos Greaves",
    "353": "Lunagaron Greaves",
    "356": "Espinas Heel",
    "371": "Hoplite's Greaves",
    "378": "Lecturer's Boots",
    "369": "Dignified Greaves",
    "383": "Barbania Boots",
    "384": "Snowshear Greaves",
    "326": "Grand God's Peer Feet",
    "333": "Bazelgeuse Greaves X",
    "314": "Damascus Greaves X",
    "311": "Kushala Crus X",
    "312": "Grand Mizuha Leg Wrap",
    "313": "Kaiser Greaves X",
    "342": "Storge Greaves",
    "352": "Malzeno Greaves",
    "374": "Charité Boots",
    "379": "Scholarly Boots",
    "380": "Commission Trousers",
    "377": "Sailor Socks",
    "355": "Archfiend Armor Sceros",
    "308": "Ibushi's Pure Foot",
    "309": "Narwa's Pure Foot",
    "327": "Valstrax Greaves - Eclipse",
    "339": "Holy Ire Hakama",
    "346": "Sinister Grudge Greaves",
    "381": "Outpost HQ Greaves",
    "507": "Blessed Feather",
    "387": "Guild Palace Greaves",
    "382": "Harp Crown",
    "361": "Azure Greaves",
    "391": "Ethereal Diadem",
    "392": "Relunea Bottom",
    "394": "Dragonsbane Greaves",
    "375": "Formal Dragon Greaves",
    "508": "Elgado Pants",
    "351": "Pride Greaves",
    "335": "Golden Lunegreaves",
    "336": "Silver Solgreaves",
    "340": "Lambent Gaiters",
    "395": "Summer Pants",
    "363": "Lien Pants",
    "407": "Fiorayne Legs",
    "408": "Utsushi Legs",
    "400": "Qurio Crown",
    "345": "Onmyo Sashiko",
    "357": "Flaming Espinas Heel",
    "416": "Risen Mizuha Gaiters",
    "396": "Fall Pants",
    "409": "Arlow Legs",
    "424": "Clockwork Greaves",
    "406": "Monocle of Clarity",
    "401": "Elfin Crown",
    "421": "Nephilim Greaves",
    "415": "Risen Kushala Crus",
    "417": "Risen Kaiser Cuisse",
    "397": "Fluffy Fur Boots",
    "410": "Hinoa Legs",
    "425": "Artian Greaves",
    "402": "Black Wing Earrings",
    "405": "Palamask",
    "362": "Shui Greaves",
    "367": "Dusk Pants",
    "422": "Rimeguard Greaves",
    "418": "Valstrax Greaves - Epoch",
    "403": "Snowy Cohoot Earmuffs",
    "393": "Face Scarf",
    "366": "Marine Pants",
    "365": "Reflet Pants",
    "364": "Lennigan Pants",
    "398": "Ran Page Legs",
    "411": "Minoto Legs",
    "370": "Alice Legs",
    "428": "Wild Legs",
    "423": "Tempest Hakama",
    "419": "Prudence Greaves",
    "435": "Buff Legs",
    "368": "Cielo Pants",
    "420": "Primordial Greaves",
}
